language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: WaxZjnRzm0ukt+H8EBi6XAqlIkPTwCh0GXW1ZwnupsNetKriEDNQUgaX8nrRpSLHC6c64SpEwRYqzFs7pyTLmwY7l2gPunxU+Eyzaq91FHgN/RXhErPUpVgApGdepLi7xY6YUu0xQ7jfGBj2CAK9effUsTftZ/ro7KV7EV3Fp4U4ARoAjVNgmTgeFecIUzQQxC2NtmfUhqb7U+x9n+lRGJc+/SVMjMEZcRf32H9HAzXCFnrstYulCyIHNT8PEctj+anarq5df16+Wo1b5AIm1gVDyxK6cwg71es/h8ymj5g8AcSD/WZFBn8bAYfinx5nGvkI/kTEoM8DocWW6eFKnE0q2oCzUsJn9pDMeaL1Bk+6lNaqNYxykcHfgK1ejpY0n3olQmrOSLhluwdS22hbp5D3S0kdG7pMAQUCzeHKn+U7hRB7iEwTkvdPYq9lASJSJx+IyAQ3hbxNqKFQ9RVNcCY36kLuaN8JbWYsNxowk3vaWmoAGKaozPYBGtoCL/ShAJw1mM/M+mjBB6eIY7b8B4sRBwQMxBfGpgyEAT0sRTQVaaQIzQD3fjBjdeWHhSSrH0XAXcvDfV5p8j5V6bZ7dmPRqXB2SxxsNrfBgSf3Tk1Z/Fwn1eUrnLdrtnIoMXFW8zQq+vCK4uHmheqCw47nyzXcpaA8VRZrggQJ323yjm0=
  file:
    - "hast-util-heading.js"
    - "hast-util-heading.min.js"
  on:
    tags: true
